### ISSUE TITLE
Documentatie is onvolledig

### ISSUE THREAD

**Issue by jakobbuis** [debolk/ledenadmin#1]
Ik probeerde vandaag de ledenadministratie aan te zetten op mijn lokale PC, maar ik weet niet hoe. Heb er mee geprutst, maar krijg het niet aan de gang. Er is geen documentatie over hoe het project in elkaar zit. Moet ik apache installeren? Heb ik node.js nodig? Hoe compile ik Coffeescript? Gebruikt het überhaupt Coffeescript? Wat doet app/js/setup.js? Waarom is dat bestand nodig? Waarom bestaat het niet?

Dat moeten we opschrijven in README.md. Ik heb een outline gecommit op feature-documentation, kun jij dat invullen?

**Comment by SleeplessByte** [comment]
Jup. [Done](https://github.com/debolk/ledenadmin). 
Je hebt alleen een intranet verbinding nodig en een moderne browser.

Intra-project documentatie is er voor zover ik weet niet.

**Comment by jakobbuis** [comment]
:+1:
