### ISSUE TITLE
Interface "alive" does not match

### ISSUE THREAD

**Issue by jakobbuis** [debolk/ledenadmin#14]
Steps to reproduce:
1) Open ledenadmin.i.bolkhuis.nl
2) Search for "Emiel"
3) Click on Emiel

Expected: Levend: Nee
Happened: Levend: Ja

Note that Emiel is currently dead in the database, you might need to kill him again if this data-entry error is fixed.

**Comment by thexa4** [comment]
Wontfix: Emiel zit op dit moment naast me en is inderdaad wel moe, maar leeft volgens mij nog wel.

**Comment by thexa4** [comment]
De template geeft geen default voor het alive veld in https://github.com/debolk/ledenadmin/blob/develop/src/app/js/views/person.coffee

**Comment by jakobbuis** [comment]
:+1:
